//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryManagementSystem.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbLibraryEntities : DbContext
    {
        public DbLibraryEntities()
            : base("name=DbLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLACTING> TBLACTING { get; set; }
        public virtual DbSet<TBLAUTHOR> TBLAUTHOR { get; set; }
        public virtual DbSet<TBLBOOK> TBLBOOK { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLCHECKOUT> TBLCHECKOUT { get; set; }
        public virtual DbSet<TBLEMPLOYEE> TBLEMPLOYEE { get; set; }
        public virtual DbSet<TBLMEMBER> TBLMEMBER { get; set; }
        public virtual DbSet<TBLPENAL> TBLPENAL { get; set; }
        public virtual DbSet<TBLABOUTUS> TBLABOUTUS { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLMESSAGES> TBLMESSAGES { get; set; }
        public virtual DbSet<TBLANNOUNCEMENTS> TBLANNOUNCEMENTS { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    
        public virtual ObjectResult<string> MostBookAuthor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostBookAuthor");
        }
    
        public virtual ObjectResult<string> MostActiveMember()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostActiveMember");
        }
    
        public virtual ObjectResult<string> MostSuccessfulEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostSuccessfulEmployee");
        }
    
        public virtual ObjectResult<string> MostReadBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostReadBook");
        }
    
        public virtual ObjectResult<Nullable<int>> TodaysRelics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TodaysRelics");
        }
    }
}
