//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLACTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLACTING()
        {
            this.TBLPENAL = new HashSet<TBLPENAL>();
        }
    
        public int ActingID { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<bool> TransactionStatus { get; set; }
        public Nullable<System.DateTime> BringMemberDate { get; set; }
    
        public virtual TBLBOOK TBLBOOK { get; set; }
        public virtual TBLEMPLOYEE TBLEMPLOYEE { get; set; }
        public virtual TBLMEMBER TBLMEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPENAL> TBLPENAL { get; set; }
    }
}
