//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBOOK()
        {
            this.TBLACTING = new HashSet<TBLACTING>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Author { get; set; }
        public string PublicationYear { get; set; }
        public string PublishingHouse { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Status { get; set; }
        public string BookPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACTING> TBLACTING { get; set; }
        public virtual TBLAUTHOR TBLAUTHOR { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
    }
}
