//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMESSAGES
    {
        public int MessageID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Subject { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
    }
}
